/**
 * DO NOT EDIT THIS FILE! This file is auto-generated by executing `gradle
 * :prism4j:regenerateDefaultGrammarLocator` and should not be edited by you!
 */
package io.noties.prism4j;

import io.noties.prism4j.languages.*;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;

public class DefaultGrammarLocator implements GrammarLocator{


        public DefaultGrammarLocator() {
                this(false, null);
        }

        /**
         * Constructor to allow initialization of all languages before requesting them. If you do not
         * want to initialize them, please use {@link #DefaultGrammarLocator()}.
         *
         * @param initLanguages set this to true or use {@link #DefaultGrammarLocator()}
         * @param prism4j the {@link Prism4j} object
         */
        public DefaultGrammarLocator(boolean initLanguages, @Nullable Prism4j prism4j) {
                if (initLanguages && prism4j != null) {
                        for (String i : languages()) {
                                grammar(prism4j, i);
                        }
                }
        }

@SuppressWarnings("ConstantConditions")
private static final Grammar NULL=new Grammar("", new ArrayList<>()){
@NotNull
@Override
public String name(){
        return null;
        }

@NotNull
@Override
public List<Token>tokens(){
        return null;
        }
        };

private final HashMap<String, Grammar>cache=new HashMap<>(3);

@Nullable
@Override
public Grammar grammar(@NotNull Prism4j prism4j,@NotNull String language){

final String name=realLanguageName(language);

        Grammar grammar=cache.get(name);
        if(grammar!=null){
        if(NULL==grammar){
        grammar=null;
        }
        return grammar;
        }

        grammar=obtainGrammar(prism4j,name);
        if(grammar==null){
        cache.put(name,NULL);
        }else{
        cache.put(name,grammar);
        }

        return grammar;
        }

@NotNull
protected String realLanguageName(@NotNull String name){
        {{real-language-name}}
        }

@Nullable
protected Grammar obtainGrammar(@NotNull Prism4j prism4j,@NotNull String name){
        {{obtain-grammar}}
        }

@Override
@NotNull
public HashSet<String> languages(){
        {{languages}}
        }
        }
